# Generated by Django 5.0.7 on 2024-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('for_him', 'For Him'), ('for_her', 'For Her'), ('dad', 'Dad'), ('mom', 'Mom'), ('graduation', 'Graduation'), ('friendship', 'Friendship')], max_length=50)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
